const profile = {
  id: '1280422772561244160',
  username: 'Jagrutee2',
  displayName: 'Jagrutee',
  photos: [
    {
      value: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png'
    }
  ],
  provider: 'twitter',
  _raw: '{"id":1280422772561244160,"id_str":"1280422772561244160","name":"Jagrutee","screen_name":"Jagrutee2","location":"","description":"","url":null,"entities":{"description":{"urls":[]}},"protected":false,"followers_count":0,"friends_count":0,"listed_count":0,"created_at":"Tue Jul 07 08:46:02 +0000 2020","favourites_count":0,"utc_offset":null,"time_zone":null,"geo_enabled":false,"verified":false,"statuses_count":4,"lang":null,"status":{"created_at":"Tue Jul 07 20:33:13 +0000 2020","id":1280600781943496704,"id_str":"1280600781943496704","text":"#JDChaavi 8 rtdtrt rfsfesfesf","truncated":false,"entities":{"hashtags":[{"text":"JDChaavi","indices":[0,9]}],"symbols":[],"user_mentions":[],"urls":[]},"source":"\\u003ca href=\\"https:\\/\\/mobile.twitter.com\\" rel=\\"nofollow\\"\\u003eTwitter Web App\\u003c\\/a\\u003e","in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"geo":null,"coordinates":null,"place":null,"contributors":null,"is_quote_status":false,"retweet_count":0,"favorite_count":0,"favorited":false,"retweeted":false,"lang":"nl"},"contributors_enabled":false,"is_translator":false,"is_translation_enabled":false,"profile_background_color":"F5F8FA","profile_background_image_url":null,"profile_background_image_url_https":null,"profile_background_tile":false,"profile_image_url":"http:\\/\\/abs.twimg.com\\/sticky\\/default_profile_images\\/default_profile_normal.png","profile_image_url_https":"https:\\/\\/abs.twimg.com\\/sticky\\/default_profile_images\\/default_profile_normal.png","profile_link_color":"1DA1F2","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"has_extended_profile":true,"default_profile":true,"default_profile_image":true,"following":false,"follow_request_sent":false,"notifications":false,"translator_type":"none","suspended":false,"needs_phone_verification":false}',
  _json: {
    id: 1280422772561244200,
    id_str: '1280422772561244160',
    name: 'Jagrutee',
    screen_name: 'Jagrutee2',
    location: '',
    description: '',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 0,
    friends_count: 0,
    listed_count: 0,
    created_at: 'Tue Jul 07 08:46:02 +0000 2020',
    favourites_count: 0,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 4,
    lang: null,
    status: {
      created_at: 'Tue Jul 07 20:33:13 +0000 2020',
      id: 1280600781943496700,
      id_str: '1280600781943496704',
      text: '#JDChaavi 8 rtdtrt rfsfesfesf',
      truncated: false,
      entities: [Object],
      source: '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: 'nl'
    },
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: null,
    profile_background_image_url_https: null,
    profile_background_tile: false,
    profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: true,
    default_profile: true,
    default_profile_image: true,
    following: false,
    follow_request_sent: false,
    notifications: false,
    translator_type: 'none',
    suspended: false,
    needs_phone_verification: false
  },
  _accessLevel: 'read'
}