const tweetsList = [
  {
    created_at: "Thu Jul 09 11:47:09 +0000 2020",
    id: 1281193167845355500,
    id_str: "1281193167845355526",
    text: "@Jagrutee2 jagz here",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "in",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "in",
  },
  {
    created_at: "Thu Jul 09 11:44:40 +0000 2020",
    id: 1281192543913250800,
    id_str: "1281192543913250821",
    text: "@Jagrutee2 hfksjdfhksjdff",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "it",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "it",
  },
  {
    created_at: "Thu Jul 09 11:39:14 +0000 2020",
    id: 1281191174733103000,
    id_str: "1281191174733103104",
    text: "@Jagrutee2  a test tweet",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "fr",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "fr",
  },
  {
    created_at: "Thu Jul 09 11:34:22 +0000 2020",
    id: 1281189953255309300,
    id_str: "1281189953255309312",
    text: "@Jagrutee2 hello there",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Jul 09 11:29:56 +0000 2020",
    id: 1281188834680553500,
    id_str: "1281188834680553474",
    text: "@Jagrutee2 hi three",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Jul 09 11:28:04 +0000 2020",
    id: 1281188366105456600,
    id_str: "1281188366105456642",
    text: "@Jagrutee2 tweshgsd sdfksjdfksdk skdfjskdf",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      result_type: "recent",
      iso_language_code: "tr",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "tr",
  },
  {
    created_at: "Thu Jul 09 09:30:15 +0000 2020",
    id: 1281158715769413600,
    id_str: "1281158715769413632",
    text: "@Jagrutee2 est",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "und",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "und",
  },
  {
    created_at: "Thu Jul 09 09:29:39 +0000 2020",
    id: 1281158565160345600,
    id_str: "1281158565160345601",
    text: "@Jagrutee2 hello",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Jul 09 09:27:48 +0000 2020",
    id: 1281158100339134500,
    id_str: "1281158100339134464",
    text: "@Jagrutee2 hey there",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1280422772561244200,
      id_str: "1280422772561244160",
      name: "Jagrutee",
      screen_name: "Jagrutee2",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Tue Jul 07 08:46:02 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 16,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Jul 09 09:00:14 +0000 2020",
    id: 1281151164206116900,
    id_str: "1281151164206116865",
    text: "Hey @Jagrutee2 thanks",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [4, 14],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 1281134489352106000,
      id_str: "1281134489352105984",
      name: "Jagz",
      screen_name: "Jagz22925494",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Thu Jul 09 07:54:05 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 4,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Jul 09 08:58:11 +0000 2020",
    id: 1281150648717738000,
    id_str: "1281150648717737984",
    text: "@Jagrutee2 please look into this",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "en",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1281134489352106000,
      id_str: "1281134489352105984",
      name: "Jagz",
      screen_name: "Jagz22925494",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Thu Jul 09 07:54:05 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 4,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Thu Jul 09 08:57:30 +0000 2020",
    id: 1281150474683482000,
    id_str: "1281150474683482113",
    text: "@Jagrutee2 test tweet",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "fr",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1281134489352106000,
      id_str: "1281134489352105984",
      name: "Jagz",
      screen_name: "Jagz22925494",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Thu Jul 09 07:54:05 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 4,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "fr",
  },
  {
    created_at: "Thu Jul 09 08:51:43 +0000 2020",
    id: 1281149020551803000,
    id_str: "1281149020551802880",
    text: "@Jagrutee2 Yo",
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: "Jagrutee2",
          name: "Jagrutee",
          id: 1280422772561244200,
          id_str: "1280422772561244160",
          indices: [0, 10],
        },
      ],
      urls: [],
    },
    metadata: {
      iso_language_code: "und",
      result_type: "recent",
    },
    source:
      '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 1280422772561244200,
    in_reply_to_user_id_str: "1280422772561244160",
    in_reply_to_screen_name: "Jagrutee2",
    user: {
      id: 1281144633192374300,
      id_str: "1281144633192374272",
      name: "Akshay",
      screen_name: "Akshay36477535",
      location: "",
      description: "",
      url: null,
      entities: {
        description: {
          urls: [],
        },
      },
      protected: false,
      followers_count: 0,
      friends_count: 0,
      listed_count: 0,
      created_at: "Thu Jul 09 08:34:26 +0000 2020",
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 1,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: "F5F8FA",
      profile_background_image_url: null,
      profile_background_image_url_https: null,
      profile_background_tile: false,
      profile_image_url:
        "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_image_url_https:
        "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
      profile_link_color: "1DA1F2",
      profile_sidebar_border_color: "C0DEED",
      profile_sidebar_fill_color: "DDEEF6",
      profile_text_color: "333333",
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: true,
      default_profile_image: true,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "none",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "und",
  },
];

module.exports = tweetsList;
